include:
  - project: pipeline/gitlab-pipeline
    file: /templates/python-golden.yml

variables:
  HAS_DEPLOYABLE: "true"
  MARVIN_NAMESPACE: "hackathon/apply-intelligence"  # Added this
  SKIP_DEPLOY_CHECKS: "true"  # Added this - seems important!
  PYTHON_BUILD_IMAGE: "harbor.indeed.tech/language-ecosystems/python"
  PYTHON_BUILD_IMAGE_TAG: "v3.10-ubuntu"
  LEMMA: "false"
  DEPLOY_TO_PROD: "false"
  PRODUCT_GROUP: "hackathon"
  QA_DEPLOY_URL: ""  # Empty like in working example
  PROD_DEPLOY_URL: ""  # Empty like in working example