include:
  - project: pipeline/gitlab-pipeline
    file: /templates/python-golden.yml

variables:
  HAS_DEPLOYABLE: "true"
  QA_DEPLOY_URL: "https://marvin.qa.indeed.tech/projects/hackathon/apply-intelligence"
  PROD_DEPLOY_URL: "https://marvin.indeed.tech/projects/hackathon/apply-intelligence"
  PYTHON_BUILD_IMAGE: "harbor.indeed.tech/language-ecosystems/python"  # This is correct
  PYTHON_BUILD_IMAGE_TAG: "v3.10-ubuntu"  # Changed to match other examples
  LEMMA: "false"
  DEPLOY_TO_PROD: "false"
  PRODUCT_GROUP: "hackathon"